name: Hello Self Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World
        run: echo Hello World from my self-hosted runner!
        shell: bash

      - name: Check Java Version
        run: java -version
        shell: bash

      - name: Print JAVA_HOME
        run: echo $JAVA_HOME
        shell: bash

      - name: Print Runner Information
        run: |
          echo Operating System:
          echo $OS

          echo Runner Name:
          echo $RUNNER_NAME

          echo Runner OS:
          echo $RUNNER_OS

          echo Runner Architecture:
          echo $RUNNER_ARCH
        shell: bash
